import 'dotenv/config';
import crypto from 'node:crypto';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import mysql from 'mysql2/promise';
import { z } from 'zod';

const missing = ['DATABASE_URL', 'JWT_SECRET', 'CORS_ORIGIN'].filter((key) => !process.env[key]);
if (missing.length) throw new Error('Variables manquantes : ' + missing.join(', '));
if (process.env.JWT_SECRET.length < 32) throw new Error('JWT_SECRET doit contenir au moins 32 caracteres.');
const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
const origins = (process.env.CORS_ORIGIN || '').split(',').map((x) => x.trim()).filter(Boolean);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin(origin, done) { return !origin || origins.includes(origin) ? done(null, true) : done(new Error('Origine non autorisee.')); }, methods: ['GET', 'POST', 'PATCH', 'DELETE'], allowedHeaders: ['Content-Type', 'Authorization'] }));
app.use(express.json({ limit: '100kb' }));
app.use(rateLimit({ windowMs: 900000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }));
const pool = mysql.createPool(process.env.DATABASE_URL);
const route = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const uuid = z.string().uuid();
const password = z.string().min(12).max(128).regex(/[a-z]/).regex(/[A-Z]/).regex(/[0-9]/);
const userInput = z.object({ email: z.string().email().max(254), password, firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), phone: z.string().trim().min(6).max(30).optional() });
const brandInput = z.object({ name: z.string().trim().min(1).max(120), slug: z.string().regex(/^[a-z0-9-]+$/).max(140), description: z.string().trim().min(1).max(10000), logoUrl: z.string().url().nullable().optional(), bannerUrl: z.string().url().nullable().optional(), accentColor: z.string().max(20).nullable().optional(), status: z.enum(['active', 'draft']), order: z.number().int().min(0).max(100000) });
const subcategoryInput = z.object({ brandId: uuid, name: z.string().trim().min(1).max(120), slug: z.string().regex(/^[a-z0-9-]+$/).max(140), description: z.string().trim().min(1).max(10000), imageUrl: z.string().url().nullable().optional(), status: z.enum(['active', 'draft']), order: z.number().int().min(0).max(100000) });
const productBase = z.object({
  brandId: uuid, subCategoryId: uuid, name: z.string().trim().min(1).max(255), slug: z.string().regex(/^[a-z0-9-]+$/).max(255), category: z.enum(['Papeterie', 'Scolaire', 'Arts & Peinture', 'Librairie', 'Bureau & Organisation']), price: z.number().nonnegative().max(9999999), promoPrice: z.number().nonnegative().max(9999999).nullable().optional(), sku: z.string().trim().min(1).max(100), stock: z.number().int().min(0).max(100000),
  isNew: z.boolean().optional(), isPromo: z.boolean().optional(), isBestSeller: z.boolean().optional(), badge: z.string().max(80).nullable().optional(), images: z.array(z.string().url()).max(12), shortDescription: z.string().trim().min(1).max(2000), description: z.string().trim().min(1).max(20000), features: z.array(z.string().max(300)).max(30), sizes: z.array(z.string().max(100)).max(30).nullable().optional(), colors: z.array(z.object({ name: z.string().max(100), hex: z.string().regex(/^#[0-9a-fA-F]{6}$/) })).max(30).nullable().optional(),
  dimensions: z.string().max(100).nullable().optional(), weight: z.string().max(100).nullable().optional(), material: z.string().max(255).nullable().optional(), actionType: z.enum(['buy_online', 'rare_call', 'rare_chat', 'rare_both']).optional(), customPhone: z.string().max(30).nullable().optional(), customWhatsapp: z.string().max(30).nullable().optional(), rareNote: z.string().max(2000).nullable().optional(), status: z.enum(['published', 'draft']),
});
const productInput = productBase.refine((x) => x.promoPrice == null || x.promoPrice <= x.price, { message: 'Prix promotionnel invalide.' });
const productPatch = productBase.partial();
const orderInput = z.object({ customer: z.object({ firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), phone: z.string().trim().min(6).max(30), address: z.string().trim().min(5).max(255), city: z.string().trim().min(2).max(80), postalCode: z.string().max(20).optional(), notes: z.string().max(1000).optional() }), items: z.array(z.object({ productId: uuid, quantity: z.number().int().min(1).max(20) })).min(1).max(30), paymentMethod: z.enum(['cod', 'card', 'pickup']) });
const json = (x) => x == null ? x : typeof x === 'string' ? JSON.parse(x) : x;
const token = (u) => jwt.sign({ sub: u.id, role: u.role }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN || '8h', issuer: 'espace-pastel-api', audience: 'espace-pastel-client' });
function auth(req, res, next) { const value = req.get('authorization')?.replace(/^Bearer\s+/i, ''); if (!value) return res.status(401).json({ error: 'Authentification requise.' }); try { req.user = jwt.verify(value, process.env.JWT_SECRET, { issuer: 'espace-pastel-api', audience: 'espace-pastel-client' }); return next(); } catch { return res.status(401).json({ error: 'Session invalide ou expiree.' }); } }
function admin(req, res, next) { return req.user.role === 'admin' ? next() : res.status(403).json({ error: 'Acces administrateur requis.' }); }
const productSelect = 'p.id, p.brand_id AS brandId, p.subcategory_id AS subCategoryId, p.name, p.slug, p.category, p.price, p.promo_price AS promoPrice, p.sku, p.stock, p.is_new AS isNew, p.is_promo AS isPromo, p.is_best_seller AS isBestSeller, p.badge, p.images, p.short_description AS shortDescription, p.description, p.features, p.sizes, p.colors, p.dimensions, p.weight, p.material, p.action_type AS actionType, p.custom_phone AS customPhone, p.custom_whatsapp AS customWhatsapp, p.rare_note AS rareNote, p.status, p.created_at AS createdAt, COALESCE((SELECT AVG(r.rating) FROM reviews r WHERE r.product_id = p.id AND r.status = \'approved\'), 0) AS rating, (SELECT COUNT(*) FROM reviews r WHERE r.product_id = p.id AND r.status = \'approved\') AS reviewCount';
function outputProduct(row) { return { ...row, price: Number(row.price), promoPrice: row.promoPrice == null ? null : Number(row.promoPrice), rating: Number(row.rating), reviewCount: Number(row.reviewCount), isNew: Boolean(row.isNew), isPromo: Boolean(row.isPromo), isBestSeller: Boolean(row.isBestSeller), images: json(row.images), features: json(row.features), sizes: json(row.sizes), colors: json(row.colors) }; }

app.get('/api/health', route(async (_q, res) => { await pool.query('SELECT 1'); res.json({ status: 'ok' }); }));
app.post('/api/auth/register', rateLimit({ windowMs: 3600000, limit: 5, standardHeaders: 'draft-8', legacyHeaders: false }), route(async (req, res) => { const x = userInput.parse(req.body); const user = { id: crypto.randomUUID(), email: x.email.toLowerCase(), role: 'customer', firstName: x.firstName, lastName: x.lastName }; await pool.execute('INSERT INTO users (id, email, password_hash, role, first_name, last_name, phone) VALUES (?, ?, ?, ?, ?, ?, ?)', [user.id, user.email, await bcrypt.hash(x.password, 12), user.role, user.firstName, user.lastName, x.phone || null]); res.status(201).json({ token: token(user), user }); }));
app.post('/api/auth/login', rateLimit({ windowMs: 900000, limit: 8, standardHeaders: 'draft-8', legacyHeaders: false }), route(async (req, res) => { const x = z.object({ email: z.string().email(), password: z.string().min(1).max(128) }).parse(req.body); const [rows] = await pool.execute('SELECT id, email, password_hash, role, first_name, last_name, phone FROM users WHERE email = ? LIMIT 1', [x.email.toLowerCase()]); const u = rows[0]; if (!u || !(await bcrypt.compare(x.password, u.password_hash))) return res.status(401).json({ error: 'Identifiants invalides.' }); res.json({ token: token(u), user: { id: u.id, email: u.email, role: u.role, firstName: u.first_name, lastName: u.last_name, phone: u.phone } }); }));
app.get('/api/auth/me', auth, route(async (req, res) => { const [users] = await pool.execute('SELECT id, email, role, first_name AS firstName, last_name AS lastName, phone, created_at AS createdAt FROM users WHERE id = ?', [req.user.sub]); const [addresses] = await pool.execute('SELECT id, label, address, city, postal_code AS postalCode, is_default AS isDefault FROM addresses WHERE user_id = ? ORDER BY is_default DESC, created_at DESC', [req.user.sub]); if (!users[0]) return res.status(401).json({ error: 'Utilisateur introuvable.' }); res.json({ ...users[0], addresses }); }));
app.patch('/api/auth/me', auth, route(async (req, res) => { const x = z.object({ firstName: z.string().trim().min(1).max(80).optional(), lastName: z.string().trim().min(1).max(80).optional(), phone: z.string().trim().min(6).max(30).nullable().optional() }).parse(req.body); const map = { firstName: 'first_name', lastName: 'last_name', phone: 'phone' }; const keys = Object.keys(x); if (!keys.length) return res.status(400).json({ error: 'Aucune modification.' }); await pool.execute('UPDATE users SET ' + keys.map((k) => map[k] + ' = ?').join(', ') + ' WHERE id = ?', [...Object.values(x), req.user.sub]); res.status(204).end(); }));
app.post('/api/addresses', auth, route(async (req, res) => { const x = z.object({ label: z.string().trim().min(1).max(80), address: z.string().trim().min(5).max(255), city: z.string().trim().min(2).max(80), postalCode: z.string().max(20).optional(), isDefault: z.boolean().optional() }).parse(req.body); const c = await pool.getConnection(); try { await c.beginTransaction(); if (x.isDefault) await c.execute('UPDATE addresses SET is_default = FALSE WHERE user_id = ?', [req.user.sub]); const newId = crypto.randomUUID(); await c.execute('INSERT INTO addresses (id, user_id, label, address, city, postal_code, is_default) VALUES (?, ?, ?, ?, ?, ?, ?)', [newId, req.user.sub, x.label, x.address, x.city, x.postalCode || null, Boolean(x.isDefault)]); await c.commit(); res.status(201).json({ id: newId }); } catch (e) { await c.rollback(); throw e; } finally { c.release(); } }));
app.delete('/api/addresses/:id', auth, route(async (req, res) => { uuid.parse(req.params.id); const [r] = await pool.execute('DELETE FROM addresses WHERE id = ? AND user_id = ?', [req.params.id, req.user.sub]); if (!r.affectedRows) return res.status(404).json({ error: 'Adresse introuvable.' }); res.status(204).end(); }));

app.get('/api/brands', route(async (_q, res) => { const [rows] = await pool.execute('SELECT id, name, slug, description, logo_url AS logoUrl, banner_url AS bannerUrl, accent_color AS accentColor, status, display_order AS displayOrder FROM brands WHERE status = ? ORDER BY display_order, name', ['active']); res.json(rows.map((x) => ({ ...x, order: x.displayOrder }))); }));
app.get('/api/subcategories', route(async (req, res) => { const sql = req.query.brandId ? 'SELECT id, brand_id AS brandId, name, slug, description, image_url AS imageUrl, status, display_order AS displayOrder FROM subcategories WHERE status = ? AND brand_id = ? ORDER BY display_order, name' : 'SELECT id, brand_id AS brandId, name, slug, description, image_url AS imageUrl, status, display_order AS displayOrder FROM subcategories WHERE status = ? ORDER BY display_order, name'; const [rows] = await pool.execute(sql, req.query.brandId ? ['active', req.query.brandId] : ['active']); res.json(rows.map((x) => ({ ...x, order: x.displayOrder }))); }));
app.get('/api/products', route(async (req, res) => { const where = ['p.status = ?']; const values = ['published']; if (req.query.brandId) { where.push('p.brand_id = ?'); values.push(req.query.brandId); } if (req.query.subCategoryId) { where.push('p.subcategory_id = ?'); values.push(req.query.subCategoryId); } if (req.query.q) { const q = '%' + String(req.query.q).slice(0, 100) + '%'; where.push('(p.name LIKE ? OR p.short_description LIKE ? OR p.category LIKE ?)'); values.push(q, q, q); } const limit = Math.min(Math.max(Number(req.query.limit) || 24, 1), 100); const [rows] = await pool.execute('SELECT ' + productSelect + ' FROM products p WHERE ' + where.join(' AND ') + ' ORDER BY p.created_at DESC LIMIT ?', [...values, limit]); res.json(rows.map(outputProduct)); }));
app.get('/api/products/:idOrSlug', route(async (req, res) => { const [rows] = await pool.execute('SELECT ' + productSelect + ' FROM products p WHERE p.status = ? AND (p.id = ? OR p.slug = ?) LIMIT 1', ['published', req.params.idOrSlug, req.params.idOrSlug]); if (!rows[0]) return res.status(404).json({ error: 'Produit introuvable.' }); res.json(outputProduct(rows[0])); }));
app.get('/api/products/:productId/reviews', route(async (req, res) => { uuid.parse(req.params.productId); const [rows] = await pool.execute('SELECT id, product_id AS productId, customer_name AS customerName, rating, comment, created_at AS date FROM reviews WHERE product_id = ? AND status = ? ORDER BY created_at DESC', [req.params.productId, 'approved']); res.json(rows); }));
app.post('/api/products/:productId/reviews', auth, route(async (req, res) => { uuid.parse(req.params.productId); const x = z.object({ rating: z.number().int().min(1).max(5), comment: z.string().trim().min(3).max(3000) }).parse(req.body); const [u] = await pool.execute('SELECT first_name, last_name, email FROM users WHERE id = ?', [req.user.sub]); if (!u[0]) return res.status(401).json({ error: 'Utilisateur introuvable.' }); await pool.execute('INSERT INTO reviews (id, product_id, user_id, customer_name, customer_email, rating, comment) VALUES (?, ?, ?, ?, ?, ?, ?)', [crypto.randomUUID(), req.params.productId, req.user.sub, u[0].first_name + ' ' + u[0].last_name, u[0].email, x.rating, x.comment]); res.status(201).json({ status: 'pending' }); }));

app.post('/api/orders', auth, route(async (req, res) => { const x = orderInput.parse(req.body); const c = await pool.getConnection(); try { await c.beginTransaction(); const ids = x.items.map((i) => i.productId); const [products] = await c.query('SELECT id, name, price, promo_price, stock, images FROM products WHERE id IN (' + ids.map(() => '?').join(',') + ') AND status = \'published\' FOR UPDATE', ids); if (products.length !== ids.length) throw Object.assign(new Error('Produit introuvable.'), { status: 400 }); let subtotal = 0; const items = []; for (const i of x.items) { const p = products.find((y) => y.id === i.productId); if (p.stock < i.quantity) throw Object.assign(new Error('Stock insuffisant : ' + p.name), { status: 409 }); const price = Number(p.promo_price ?? p.price); subtotal += price * i.quantity; items.push({ productId: p.id, productName: p.name, price, quantity: i.quantity, image: json(p.images)[0] || '' }); await c.execute('UPDATE products SET stock = stock - ? WHERE id = ?', [i.quantity, i.productId]); } const shippingFee = subtotal >= 100 ? 0 : 7; const newId = crypto.randomUUID(); const number = 'EP-' + new Date().getFullYear() + '-' + crypto.randomUUID().slice(0, 8).toUpperCase(); await c.execute('INSERT INTO orders (id, order_number, user_id, customer_json, items_json, subtotal, shipping_fee, total, payment_method, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [newId, number, req.user.sub, JSON.stringify(x.customer), JSON.stringify(items), subtotal, shippingFee, subtotal + shippingFee, x.paymentMethod, 'pending']); await c.commit(); res.status(201).json({ id: newId, orderNumber: number, subtotal, shippingFee, total: subtotal + shippingFee, status: 'pending' }); } catch (e) { await c.rollback(); throw e; } finally { c.release(); } }));
const ordersQuery = 'SELECT id, order_number AS orderNumber, user_id AS userId, customer_json AS customer, items_json AS items, subtotal, shipping_fee AS shippingFee, total, payment_method AS paymentMethod, status, created_at AS createdAt FROM orders';
const orderOutput = (rows) => rows.map((x) => ({ ...x, subtotal: Number(x.subtotal), shippingFee: Number(x.shippingFee), total: Number(x.total), customer: json(x.customer), items: json(x.items) }));
app.get('/api/orders', auth, route(async (req, res) => { const [rows] = await pool.execute(ordersQuery + ' WHERE user_id = ? ORDER BY created_at DESC', [req.user.sub]); res.json(orderOutput(rows)); }));

const brandMap = { name: 'name', slug: 'slug', description: 'description', logoUrl: 'logo_url', bannerUrl: 'banner_url', accentColor: 'accent_color', status: 'status', order: 'display_order' };
const subMap = { brandId: 'brand_id', name: 'name', slug: 'slug', description: 'description', imageUrl: 'image_url', status: 'status', order: 'display_order' };
function patchSql(table, map, x, target) { const keys = Object.keys(x); if (!keys.length) return null; return [ 'UPDATE ' + table + ' SET ' + keys.map((k) => map[k] + ' = ?').join(', ') + ' WHERE id = ?', [...Object.values(x), target] ]; }
function adminCrud(path, table, schema, map, columns) { app.post(path, auth, admin, route(async (req, res) => { const x = schema.parse(req.body); const newId = crypto.randomUUID(); const keys = Object.keys(x); await pool.execute('INSERT INTO ' + table + ' (id, ' + keys.map((k) => columns[k]).join(', ') + ') VALUES (?, ' + keys.map(() => '?').join(', ') + ')', [newId, ...Object.values(x)]); res.status(201).json({ id: newId }); })); app.patch(path + '/:id', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const q = patchSql(table, map, schema.partial().parse(req.body), req.params.id); if (!q) return res.status(400).json({ error: 'Aucune modification.' }); const [r] = await pool.execute(q[0], q[1]); if (!r.affectedRows) return res.status(404).json({ error: 'Element introuvable.' }); res.status(204).end(); })); app.delete(path + '/:id', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const [r] = await pool.execute('DELETE FROM ' + table + ' WHERE id = ?', [req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Element introuvable.' }); res.status(204).end(); })); }
adminCrud('/api/admin/brands', 'brands', brandInput, brandMap, brandMap);
adminCrud('/api/admin/subcategories', 'subcategories', subcategoryInput, subMap, subMap);
const productMap = { brandId: 'brand_id', subCategoryId: 'subcategory_id', name: 'name', slug: 'slug', category: 'category', price: 'price', promoPrice: 'promo_price', sku: 'sku', stock: 'stock', isNew: 'is_new', isPromo: 'is_promo', isBestSeller: 'is_best_seller', badge: 'badge', images: 'images', shortDescription: 'short_description', description: 'description', features: 'features', sizes: 'sizes', colors: 'colors', dimensions: 'dimensions', weight: 'weight', material: 'material', actionType: 'action_type', customPhone: 'custom_phone', customWhatsapp: 'custom_whatsapp', rareNote: 'rare_note', status: 'status' };
const productValue = (key, value) => ['images', 'features', 'sizes', 'colors'].includes(key) && value != null ? JSON.stringify(value) : value;
app.post('/api/admin/products', auth, admin, route(async (req, res) => { const x = productInput.parse(req.body); const keys = Object.keys(x); const newId = crypto.randomUUID(); await pool.execute('INSERT INTO products (id, ' + keys.map((k) => productMap[k]).join(', ') + ') VALUES (?, ' + keys.map(() => '?').join(', ') + ')', [newId, ...keys.map((k) => productValue(k, x[k]))]); res.status(201).json({ id: newId }); }));
app.patch('/api/admin/products/:id', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const x = productPatch.parse(req.body); const keys = Object.keys(x); if (!keys.length) return res.status(400).json({ error: 'Aucune modification.' }); const [r] = await pool.execute('UPDATE products SET ' + keys.map((k) => productMap[k] + ' = ?').join(', ') + ' WHERE id = ?', [...keys.map((k) => productValue(k, x[k])), req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Produit introuvable.' }); res.status(204).end(); }));
app.delete('/api/admin/products/:id', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const [r] = await pool.execute('DELETE FROM products WHERE id = ?', [req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Produit introuvable.' }); res.status(204).end(); }));
app.patch('/api/admin/products/:id/stock', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const { stock } = z.object({ stock: z.number().int().min(0).max(100000) }).parse(req.body); const [r] = await pool.execute('UPDATE products SET stock = ? WHERE id = ?', [stock, req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Produit introuvable.' }); res.status(204).end(); }));
app.get('/api/admin/orders', auth, admin, route(async (_q, res) => { const [rows] = await pool.execute(ordersQuery + ' ORDER BY created_at DESC'); res.json(orderOutput(rows)); }));
app.patch('/api/admin/orders/:id/status', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const { status } = z.object({ status: z.enum(['pending', 'preparing', 'processing', 'shipped', 'delivered', 'cancelled']) }).parse(req.body); const [r] = await pool.execute('UPDATE orders SET status = ? WHERE id = ?', [status, req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Commande introuvable.' }); res.status(204).end(); }));
app.get('/api/admin/reviews', auth, admin, route(async (_q, res) => { const [rows] = await pool.execute('SELECT id, product_id AS productId, user_id AS userId, customer_name AS customerName, customer_email AS customerEmail, rating, comment, status, created_at AS date FROM reviews ORDER BY created_at DESC'); res.json(rows); }));
app.patch('/api/admin/reviews/:id', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const { status } = z.object({ status: z.enum(['pending', 'approved', 'rejected']) }).parse(req.body); const [r] = await pool.execute('UPDATE reviews SET status = ? WHERE id = ?', [status, req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Avis introuvable.' }); res.status(204).end(); }));
app.delete('/api/admin/reviews/:id', auth, admin, route(async (req, res) => { uuid.parse(req.params.id); const [r] = await pool.execute('DELETE FROM reviews WHERE id = ?', [req.params.id]); if (!r.affectedRows) return res.status(404).json({ error: 'Avis introuvable.' }); res.status(204).end(); }));
app.use((_q, res) => res.status(404).json({ error: 'Route introuvable.' }));
app.use((error, _q, res, _next) => { if (error instanceof z.ZodError) return res.status(400).json({ error: 'Donnees invalides.', details: error.flatten().fieldErrors }); if (error.code === 'ER_DUP_ENTRY') return res.status(409).json({ error: 'Cette valeur existe deja.' }); if (error.code === 'ER_NO_REFERENCED_ROW_2') return res.status(400).json({ error: 'Reference invalide.' }); if (error.status) return res.status(error.status).json({ error: error.message }); console.error(error); return res.status(500).json({ error: 'Erreur interne.' }); });
app.listen(Number(process.env.PORT || 3001), () => console.log('API Espace Pastel demarree.'));
